customhost = "database-2.cupqwfs7wt88.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "soozhiyao_employee"
custombucket = "soozhiyao_employee"
customregion = "us-east-1"
